### ISSUE TITLE
a few questions

### ISSUE THREAD

**Issue by victorconan** [futianfan/clinical-trial-outcome-prediction#8]
Hi, Thanks for open sourcing this. I have a few questions regarding the paper:

1. How the outcome label is determined? It seems the outcome label comes from IQVIA so the process of generating it was not shown in this repo. In the paper, it was described as `The trial is labelled as success if p-value is less than
0.05 and negative if p-value is higher than 0.05`. I am not sure if this is also applicable for Phase I trials. Could you elaborate more on that?
2. How does ADMET pretraining help with Phase II prediction? Since majority of Phase II trials failed due to efficacy, I am not sure why pretraining ADMET could help with the predictions. Instead, understanding the disease-target relation may help.

**Comment by futianfan** [comment]
thanks for your interest!

1. we use iqvia labels instead of p-value based labels. Our latest experimental design is in cell pattern paper
https://www.sciencedirect.com/science/article/pii/S2666389922000186#, which uses iqvia labels and are manually labelled and more reliable. in contrast, the arxiv version (based on p-value, not reliable sometimes) is the older one. 

2. phase 2 and 3 would also focus on safety issue, though not so much compared with phase i, so we think admet module would be still useful.

**Comment by victorconan** [comment]
Thanks for the quick reply!
